name: getx_super_snackbar
description: |
  GetX Super Snackbar is a powerful, flexible, and easy-to-use snackbar package for Flutter applications, 
  built on top of the popular GetX package. It allows developers to create highly customizable snackbars 
  that can be used to display a variety of messages such as success, error, warning, and informational alerts.

  With GetX Super Snackbar, you can:

  - Customize the appearance of your snackbars with different colors, icons, and animations.
  - Easily integrate with existing GetX projects, ensuring a seamless developer experience.
  - Display snackbars with or without user interaction, and control their duration and position on the screen.
  - Use predefined themes or create your own to maintain a consistent look and feel throughout your application.

  This package is ideal for developers looking to enhance user feedback mechanisms in their Flutter apps, 
  providing users with instant, visually appealing notifications that are easy to implement and manage."

version: 1.0.2
homepage: https://github.com/claviertech/getx_super_snackbar
repository: https://github.com/claviertech/getx_super_snackbar
issue_tracker: https://github.com/claviertech/getx_super_snackbar/issues
documentation: https://github.com/claviertech/getx_super_snackbar/wiki

environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
